services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: femee-sqlserver
    environment:
      SA_PASSWORD: "F_CLAN@GG123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
